### PR TITLE
functions to verify and escape string parameters

### PR DESCRIPTION
**Pull request by asjongers**

### CODE REVIEW

**Comment by cecton** [comment]
@erikap well you can check the grammar: https://www.w3.org/TR/2013/REC-sparql11-query-20130321/#rSTRING_LITERAL1

...but I think you're safe if you escape `\`, `"` and `'`.  On the other hand, if you want to check that a string is properly escaped, I translated the STRING_LITERAL* to regex you can use directly.

**Comment by erikap** [comment]
Thx @asjongers @cecton for adding this feature!

**Comment by cecton** [comment]
Actually you also have to escape new lines and carriage returns :innocent:

**Comment by cecton** [comment]
Also @asjongers you forgot to add the `"` before and after the string. Was it intended?

**Pull request merged**
